/**
 * Runs the cohort and writes sim/report.md.
 *
 *   npm run sim
 *
 * Free and offline. No model is called: every question already exists in the three
 * built-in packs, and a refutation's effect is a number from sim/personas.ts rather
 * than text from Mistral. What is exercised is the engine — information-gain
 * ordering, the posterior, the gating rule, the recheck builder, CBM scoring — over
 * 36 complete runs, which is more paths through it than a person will click in a
 * week.
 *
 * Also writes sim/sessions.json in the shape localStorage holds, so /dashboard can
 * be screenshotted with a populated history instead of one lonely run.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { PACKS } from "@/lib/packs";
import { accuracy, cbmMax, cbmScore, countByQuadrant, overconfidence } from "@/lib/scoring";
import type { Response, SessionRecord } from "@/lib/types";
import { runSession, type SimResult } from "./learner";
import { PERSONAS } from "./personas";
import { applyPolicy, gatingCounts, recovery, type PolicyName } from "./policy";
import { rng } from "./rng";

const LIFT_SWEEP = [0, 0.25, 0.5, 0.75, 1];
const POLICIES: PolicyName[] = ["targeted", "blanket", "plain"];

/**
 * Cohorts drawn per persona and pack, so a persona's numbers rest on 168 answers
 * rather than 21. One run each looked decisive and was mostly the coin: a learner
 * who knows 45% of the material can answer 19% of one pack correctly without
 * anything being wrong, and a table that reports that as their accuracy is a table
 * reporting noise.
 */
const REPEATS = 8;

function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}

function one(n: number): string {
  return n.toFixed(1);
}

/**
 * One cohort: every persona through every pack, seeded on the repeat index.
 *
 * Deliberately not seeded on the lift assumption. The probe round and the repair
 * set do not depend on it — only whether a correction sticks does — so the sweep
 * varies the assumption over one fixed set of learners and misses. Reseeding per
 * row was the first version of this, and it made the table non-monotone by changing
 * the cohort underneath the thing being measured.
 */
function cohort(repeat: number, liftScale = 1): SimResult[] {
  const results: SimResult[] = [];
  for (const [p, persona] of PERSONAS.entries()) {
    for (const [k, pack] of PACKS.entries()) {
      const random = rng(1_000_003 * (repeat + 1) + 1000 * (p + 1) + 17 * (k + 1));
      results.push(runSession(pack, persona, random, liftScale));
    }
  }
  return results;
}

function sureWrongRecovered(results: SimResult[]): { held: number; cleared: number } {
  let held = 0;
  let cleared = 0;
  for (const result of results) {
    const after = new Map(
      result.recheck.map((r) => [r.itemId.replace(/-v$/, ""), r]),
    );
    for (const treatment of result.treatments) {
      if (treatment.kind !== "refutation") continue;
      const again = after.get(treatment.itemId);
      if (!again) continue;
      held += 1;
      if (again.correct) cleared += 1;
    }
  }
  return { held, cleared };
}

describe("simulated cohort", () => {
  it("runs twelve learners through three packs and writes the report", () => {
    // One cohort for the dashboard history, and REPEATS of them for the numbers.
    const baseline = cohort(0);
    const wide = Array.from({ length: REPEATS }, (_, i) => cohort(i)).flat();
    expect(baseline).toHaveLength(PERSONAS.length * PACKS.length);

    const lines: string[] = [];
    lines.push("# Simulated cohort");
    lines.push("");
    lines.push(
      `Generated by \`npm run sim\`. Twelve personas, three packs, ${REPEATS} draws each, ${wide.length} complete runs, no model calls and no people.`,
    );
    lines.push("");
    lines.push("## What this is and is not");
    lines.push("");
    lines.push(
      "Every learner here is a set of numbers in `sim/personas.ts`: how much they know, how certain that makes them, and how stubbornly a belief survives being corrected. The last of those is an assumption, so nothing below is evidence that refutation works on people. Two things it does measure honestly.",
    );
    lines.push("");
    lines.push(
      "First, whether `lib/belief.ts` names the misconception the learner actually held. The learner's belief is drawn from the same hypothesis space the model searches, so this is a fact about the arithmetic, checkable and not assumed.",
    );
    lines.push("");
    lines.push(
      "Second, what the gating rule costs and saves against refuting every wrong answer, swept across the full range of the assumption rather than resting on one value of it.",
    );
    lines.push("");

    // ---- Per-persona behaviour -------------------------------------------------
    lines.push("## The cohort");
    lines.push("");
    lines.push("| Learner | Style | Knows | Right | Certainty said | Gap | CBM | Sure and wrong |");
    lines.push("| --- | --- | --- | --- | --- | --- | --- | --- |");

    for (const persona of PERSONAS) {
      const mine = wide.filter((r) => r.persona.id === persona.id);
      const probe: Response[] = mine.flatMap((r) => r.probe);
      const over = overconfidence(probe);
      const quads = countByQuadrant(probe);
      lines.push(
        `| ${persona.name} | ${persona.confidence} | ${pct(persona.soundRate)} | ${pct(
          accuracy(probe),
        )} | ${pct(accuracy(probe) + over)} | ${over >= 0 ? "+" : ""}${Math.round(
          over * 100,
        )} | ${cbmScore(probe)}/${cbmMax(probe)} | ${quads.SURE_WRONG} |`,
      );
    }
    lines.push("");
    lines.push(
      "`Knows` is the persona's stated command of the material and `Right` is what they scored, so the two columns together are a check that the simulation does what its own configuration says. `Right` sits below `Knows` by design: a learner drops answers to their slip rate, and a concept they hold no misconception about is not a concept every question offers them cleanly. Yuki is the widest gap in the table and also has the highest slip rate in the cohort, which is the shape that should follow.",
    );
    lines.push("");
    lines.push(
      "The gap column is the app's overconfidence measure, and it separates the cohort the way the personas were written to: the overconfident learners sit positive, the cautious ones negative, and CBM punishes the first group without punishing an honest guess.",
    );
    lines.push("");

    // ---- Gating --------------------------------------------------------------
    const gates = gatingCounts(wide);
    lines.push("## The gating rule");
    lines.push("");
    lines.push(
      `Across ${wide.length} runs the app wrote ${gates.refutations} personalised refutations and ${gates.plain} plain explanations. Every refutation went to an answer that was wrong and held with certainty (${gates.sureWrongTreated} of ${gates.refutations}), and none went to an answer flagged as a guess (${gates.guessedWrongRefuted}). That is the rule the whole app rests on, exercised rather than asserted.`,
    );
    lines.push("");

    // ---- Belief recovery -----------------------------------------------------
    const totals = wide
      .map((r) => recovery(r.pack, r.probe, r.beliefs))
      .reduce((a, b) => ({
        concepts: a.concepts + b.concepts,
        identified: a.identified + b.identified,
        heldMisconception: a.heldMisconception + b.heldMisconception,
        misconceptionsNamed: a.misconceptionsNamed + b.misconceptionsNamed,
        sureWrongConcepts: a.sureWrongConcepts + b.sureWrongConcepts,
        sureWrongNamed: a.sureWrongNamed + b.sureWrongNamed,
      }));

    lines.push("## Did the belief model name the right belief");
    lines.push("");
    lines.push("| Case | Concepts | Named exactly | Rate |");
    lines.push("| --- | --- | --- | --- |");
    lines.push(
      `| Every concept asked about | ${totals.concepts} | ${totals.identified} | ${pct(
        totals.identified / totals.concepts,
      )} |`,
    );
    lines.push(
      `| Learner held a misconception | ${totals.heldMisconception} | ${totals.misconceptionsNamed} | ${pct(
        totals.misconceptionsNamed / Math.max(1, totals.heldMisconception),
      )} |`,
    );
    lines.push(
      `| Wrong and certain about it | ${totals.sureWrongConcepts} | ${totals.sureWrongNamed} | ${pct(
        totals.sureWrongNamed / Math.max(1, totals.sureWrongConcepts),
      )} |`,
    );
    lines.push("");
    lines.push(
      "The last row is the one that matters, because it is the case the app acts on: a confidently wrong answer is where a refutation gets written, and naming the wrong belief there would mean arguing against something the learner never thought. Chance would be roughly one in the number of candidate beliefs per concept.",
    );
    lines.push("");

    // ---- Policy sweep --------------------------------------------------------
    lines.push("## Targeting against refuting everything");
    lines.push("");
    lines.push(
      "`lift` is the assumption under test: how much of a belief's stubbornness a personalised refutation gets through that a plain statement of the answer does not. At `lift = 0` the two are worth the same and the app's thesis is false by construction.",
    );
    lines.push("");
    lines.push("| lift | Targeted corrections | Refute everything | Plain only | Calls: targeted | Calls: everything |");
    lines.push("| --- | --- | --- | --- | --- | --- |");

    const totalsFor = (policy: PolicyName, lift: number) =>
      wide
        .map((r) => applyPolicy(r, policy, lift))
        .reduce((a, b) => ({
          calls: a.calls + b.calls,
          corrections: a.corrections + b.corrections,
          slips: a.slips + b.slips,
          beliefs: a.beliefs + b.beliefs,
        }));

    for (const lift of LIFT_SWEEP) {
      const [targeted, blanket, plain] = POLICIES.map((policy) =>
        totalsFor(policy, lift),
      );
      lines.push(
        `| ${lift} | ${one(targeted!.corrections)} | ${one(blanket!.corrections)} | ${one(
          plain!.corrections,
        )} | ${targeted!.calls} | ${blanket!.calls} |`,
      );
    }
    lines.push("");
    lines.push(
      "The call counts do not move across rows because the assumption changes what a refutation achieves, not who gets one. The same cohort and the same misses are used for every row, so the only thing varying down the table is the assumption itself.",
    );
    lines.push("");

    const targetedAtOne = totalsFor("targeted", 1);
    const blanketAtOne = totalsFor("blanket", 1);
    const plainAtOne = totalsFor("plain", 1);

    lines.push(
      `At the personas' own stated lift, targeting clears ${one(
        targetedAtOne.corrections,
      )} of ${targetedAtOne.beliefs} held misconceptions. Refuting every wrong answer clears ${one(
        blanketAtOne.corrections,
      )}, which is ${pct(
        1 - targetedAtOne.corrections / blanketAtOne.corrections,
      )} more, for ${blanketAtOne.calls - targetedAtOne.calls} extra paid calls (${pct(
        blanketAtOne.calls / targetedAtOne.calls - 1,
      )} more spend). Explaining plainly every time and never refuting clears ${one(
        plainAtOne.corrections,
      )} for no calls at all. The corrections targeting gives up are on answers the learner flagged as a guess, which is the trade the app makes on purpose: those are also the learners the literature says a refutation is worst for.`,
    );
    lines.push("");
    lines.push(
      `A fair reading of that table: the case for the gating rule is not that it corrects more, it is that it declines ${pct(
        1 - targetedAtOne.calls / blanketAtOne.calls,
      )} of the calls and still gets ${pct(
        targetedAtOne.corrections / blanketAtOne.corrections,
      )} of the effect, because the calls it declines are aimed at beliefs nobody held. At lift 0 every column is identical, which is the honest statement that this app's whole premise is an empirical bet.`,
    );
    lines.push("");

    // ---- Sampled before and after -------------------------------------------
    const recovered = sureWrongRecovered(wide);
    lines.push("## The sampled run");
    lines.push("");
    lines.push(
      `In the ${wide.length} runs as actually rolled, ${recovered.held} beliefs were held with certainty and got them wrong. ${recovered.cleared} of those were answered correctly on the reworded recheck question, ${pct(
        recovered.cleared / Math.max(1, recovered.held),
      )}. This number is downstream of the assumption above and is here to show the pipeline end to end, not to stand as a finding.`,
    );
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push(
      "Reproduce with `npm run sim`. The generator is seeded per persona and pack, so the cohort is the same cohort every run and a change in these numbers means a change in the engine.",
    );
    lines.push("");

    const out = path.resolve(process.cwd(), "sim");
    writeFileSync(path.join(out, "report.md"), lines.join("\n"), "utf8");

    // History in the shape localStorage holds, for a populated dashboard shot.
    const sessions: SessionRecord[] = baseline.map((r) => r.session);
    writeFileSync(
      path.join(out, "sessions.json"),
      `${JSON.stringify(sessions, null, 2)}\n`,
      "utf8",
    );

    // The report is only worth writing if the engine actually ran.
    expect(gates.refutations).toBeGreaterThan(0);
    expect(gates.guessedWrongRefuted).toBe(0);
    expect(totals.concepts).toBeGreaterThan(0);
  });
});
